version: "3.8"

services:
  zentronew:
    build: .

    networks:
      - zentronet

    deploy:
      replicas: 1

      labels:
        - traefik.enable=true

        - traefik.http.routers.zentronew.rule=Host(`zentroplay.net`)
        - traefik.http.routers.zentronew.entrypoints=websecure
        - traefik.http.routers.zentronew.tls.certresolver=letsencrypt

        - traefik.http.services.zentronew.loadbalancer.server.port=80

networks:
  zentronet:
    external: true
